### ISSUE TITLE
Errore nel caricamento di un immagine

### ISSUE THREAD

**Issue by iannellog** [fioriofederico/labyrinth_22-23#12]
Hp provato a eseguire il programma con il comando:

> python main.py

ho scelto l'opzione 2, ho fornito il path assoluto dell'immagine e il programma ha generato un errore dopo aver fatto delle cose.
Ho provato a capire quale fosse il problema guardando il codice, ma non ci sono riuscito.
L'errore che ottengo è:

> Traceback (most recent call last):
  File "/Users/iannello/Home/Didattica/Programmazione/2022-2023/Progetti/Calandra-Fiorio-Papa/labyrinth_22-23/main.py", line 121, in <module>
    main_menu()
  File "/Users/iannello/Home/Didattica/Programmazione/2022-2023/Progetti/Calandra-Fiorio-Papa/labyrinth_22-23/main.py", line 36, in main_menu
    upload_image(menu)
  File "/Users/iannello/Home/Didattica/Programmazione/2022-2023/Progetti/Calandra-Fiorio-Papa/labyrinth_22-23/main.py", line 101, in upload_image
    json_to_path()
  File "/Users/iannello/Home/Didattica/Programmazione/2022-2023/Progetti/Calandra-Fiorio-Papa/labyrinth_22-23/utilities/funzioni_finali.py", line 139, in json_to_path
    img = [f for f in os.listdir(img_files) if f.endswith('.tiff')]
FileNotFoundError: [Errno 2] No such file or directory: '/Users/iannello/Home/Didattica/Programmazione/2022-2023/Progetti/Calandra-Fiorio-Papa/labyrinth_22-23/./img_input/'

da notare che il path:

> /Users/iannello/Home/Didattica/Programmazione/2022-2023/Progetti/Calandra-Fiorio-Papa/labyrinth_22-23

è quello della workinig directory (cioé da dove ho lanciato il programma).

**Comment by vectorstain** [comment]
Thanks your feedback is very important to us to develop our application. 
Our team has solved the reported issue. Now a new version have been published and the readme was updated with few examples.
